name: Terraform Lint

on:
  push:
    paths:
      - "**/**.tf"
    branches:
      - main
  pull_request:
    paths:
      - "**/**.tf"
    branches:
      - main

jobs:
  lint:
    name: Lint Workflow Files
    runs-on: ubuntu-20.04

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Lint Terraform
      uses: actionshub/terraform-lint@a1375ebf62bdf822f7bddab3d0faba0ae8df4bd4