name: Workflows Lint

on:
  push:
    paths:
      - .github/workflows/*.yaml
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/*.yaml
    branches:
      - main

jobs:
  run-linters:
    name: Lint Workflows
    runs-on: ubuntu-20.04

    steps:
      - name: Check repository out
        uses: actions/checkout@v2
      
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/7e7677cc342d85fb954dd194a05a20a130aaba6d/scripts/download-actionlint.bash)
        shell: bash

      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash